variables:
  DEBIAN_FRONTEND: noninteractive
  GIT_STRATEGY: clone
  REVISION: "1"

cache:
  key: none
  paths: []
  policy: pull

.build: &build
  stage: build
  tags:
    - docker
    - linux
  before_script:
    - apt-get update -q
    - apt-get install -qy --no-install-recommends
        build-essential
        cdbs
        devscripts
        dh-autoreconf
        dh-python
        fakeroot
        git
        lintian
        pkg-config
    - if [ "$ARCH" != "$(dpkg-architecture -qDEB_BUILD_ARCH)" ]; then
        dpkg --add-architecture $ARCH;
        apt-get update -q;
        apt-get install -qy --no-install-recommends
          crossbuild-essential-$ARCH
          libstdc++6:$ARCH
          qemu-user-static;
      fi
    - apt-get install -qy --no-install-recommends
        libbluetooth-dev:$ARCH
    - apt-get install -qy --no-install-recommends
        cython
        libpython-dev:$ARCH
        python
        python-setuptools
        python-wheel
    - apt-get install -qy --no-install-recommends
        cython3
        libpython3-dev:$ARCH
        python3
        python3-setuptools
        python3-wheel
    - apt-get install -qy --no-install-recommends
        doxygen
        graphviz
  script:
    - SOURCE=$(dpkg-parsechangelog -S Source)
    - VERSION=$(dpkg-parsechangelog -S Version | sed 's/\-.*$//')
    - sed -i "s/[)] UNRELEASED/-0$DIST$REVISION) $SUITE/" debian/changelog
    - if [ "$ARCH" = "$(dpkg-architecture -qDEB_BUILD_ARCH)" ]; then
        git archive -o ../${SOURCE}_${VERSION}.orig.tar HEAD;
        xz ../${SOURCE}_${VERSION}.orig.tar;
      else
        export CONFIG_SITE=/etc/dpkg-cross/cross-config.$ARCH;
      fi
    - debuild $DEBUILD_OPTS
  after_script:
    - SOURCE=$(dpkg-parsechangelog -S Source)
    - VERSION=$(dpkg-parsechangelog -S Version | sed 's/\-.*$//')
    - mkdir -p build
    - mv ../${SOURCE}_${VERSION}* ../*.deb ../*.ddeb build/
  artifacts:
    paths:
      - build/
    expire_in: 1 week

build:bionic-amd64:
  <<: *build
  image: ubuntu:bionic
  variables:
    ARCH: amd64
    DEBUILD_OPTS: -uc -us
    DIST: bionic
    SUITE: $DIST

build:buster-amd64:
  <<: *build
  image: debian:buster
  variables:
    ARCH: amd64
    DEBUILD_OPTS: -uc -us
    DIST: buster
    SUITE: $DIST

build:buster-armhf:
  <<: *build
  image: debian:buster
  variables:
    ARCH: armhf
    DEBUILD_OPTS: -a$ARCH -B -uc -us
    DIST: buster
    SUITE: $DIST

build:buster-arm64:
  <<: *build
  image: debian:buster
  variables:
    ARCH: arm64
    DEBUILD_OPTS: -a$ARCH -B -uc -us
    DIST: buster
    SUITE: $DIST
